pipeline {
    agent any
    environment {
        // Set any environment variables here (e.g., database credentials)
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image using the Dockerfile
                    sh 'docker-compose -f docker-compose.yml build'
                }
            }
        }
        stage('Run Tests') {
            steps {
                script {
                    // Run tests inside the Docker container
                    sh 'docker-compose run web python manage.py test'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    // Deploy your application (e.g., to a production server)
                    // Replace with your deployment command
                    sh 'docker-compose up -d'
                }
            }
        }
    }
    post {
        always {
            // Clean up after the build process
            sh 'docker-compose down'
        }
    }
}
